dataset:
  path: "/gluster/data/dune/niclane/"
  file: "nlane_prod_strange_resample_fhc_run2_fhc_reco2_reco2_trainingimage_signal_lambdamuon_1000_ana.root"
  tree: "imageanalyser/ImageTree"
  width: 512
  height: 512
  planes: ["U", "V", "W"]
  induction_plane: 2
train:
  n_epochs: 20
  batch_size: 8
  learning_rate: 0.001
  checkpoint_directory: "./chk"
  input_channels: 3
  numer_classes: 6
  segmentation_classes: 5
  filters: 32
  dropout: 0.1
  feature_dimensions: 128
  optimiser: Adam
  weight_decay: 0.0001