train:
  objective: classification
  num_epochs: 20
  batch_size: 8
  lr: 0.001
  ckpt_dir: "./checkpoints"
  temp: 0.1

model:
  arch: UResNetEncoder
  in_channels: 3
  num_classes: 6
  seg_classes: 2
  filters: 32
  dropout: 0.1
  feat_dim: 128
  optimizer: Adam
  weight_decay: 0.0001

dataset:
  path: "/gluster/data/dune/niclane/nlane_prod_strange_resample_fhc_run2_fhc_reco2_reco2_trainingimage_signal_lambdamuon_ana.root"
  tree: "imageanalyser/ImageTree"
  dims:
    width: 512
    height: 512
  planes: ["U", "V", "W"]
  ind_plane_idx: 2
  filters:
    event_type: all