dataset:
  path: "/gluster/data/dune/niclane/"
  file: "prod_strange_resample_fhc_run2_fhc_reco2_reco2_trainingimageanalyser_signal_lambdamuon_1_new_analysis.root"
  tree: "imageanalyser/ImageTree"
  width: 512
  height: 512
  planes: ["U", "V", "W"]
  induction_plane: 2
train:
  num_epochs: 1
  batch_size: 64
  learning_rate: 0.001
  checkpoint_directory: "./chk"
  input_channels: 3
  numer_classes: 7
  segmentation_classes: 7
  filters: 32
  dropout: 0.1
  feature_dimensions: 128
  optimiser: Adam
  weight_decay: 0.0001